apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-app
  namespace: wms-proto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: audit-app
  template:
    metadata:
      labels:
        app: audit-app
    spec:
      imagePullSecrets:
        - name: nexus-docker-creds
      initContainers:
        - name: init-db-schemas
          image: postgres:12.8
          env:
            - name: PGPASSWORD
              value: postgres
          command:
            - sh
            - -c
            - |
              until pg_isready -h audit-postgres -p 5432 -U postgres; do
                sleep 2
              done
              psql -h audit-postgres -U postgres -d wms -c 'CREATE SCHEMA IF NOT EXISTS audit;'
              psql -h audit-postgres -U postgres -d wms -c 'ALTER DATABASE wms SET search_path TO audit, public;'
      containers:
        - name: audit-app
          image: 10.96.191.117:8082/audit-app:jenkins-18
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
            - name: DEPLOY_ENV
              value: proto
            - name: DB_URL
              value: jdbc:postgresql://audit-postgres:5432/wms
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "audit-kafka:9094"
            - name: APP_SECURITY_OIDC_CLIENT_ID
              value: "wms-audit"
            - name: APP_SECURITY_OIDC_CLIENT_SECRET
              value: ""
            - name: APP_SECURITY_OIDC_VERIFY_TOKEN_AUDIENCE
              value: "false"
            - name: SERVER_PORT
              value: "8085"
          readinessProbe:
            httpGet:
              path: /api/audit/actuator/health/readiness
              port: 8085
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/audit/actuator/health/liveness
              port: 8085
            initialDelaySeconds: 180
            periodSeconds: 10
