apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  namespace: wms-proto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      imagePullSecrets:
        - name: nexus-docker-creds
      initContainers:
        - name: init-db-schemas
          image: 10.96.191.117:8082/inventory-app:jenkins-4
          env:
            - name: PGPASSWORD
              value: postgres
          command:
            - sh
            - -c
            - |
              until pg_isready -h inventory-postgres -p 5432 -U postgres; do
                sleep 2
              done
              psql -h inventory-postgres -U postgres -d wms -c 'CREATE SCHEMA IF NOT EXISTS inventory;'
              psql -h inventory-postgres -U postgres -d wms -c 'ALTER DATABASE wms SET search_path TO inventory, public;'
      containers:
        - name: inventory-app
          image: 10.96.191.117:8082/inventory-app:jenkins-4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
            - name: DEPLOY_ENV
              value: proto
            - name: DB_URL
              value: jdbc:postgresql://inventory-postgres:5432/wms
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: inventory-kafka:9094
            - name: SERVER_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /api/inventory/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/inventory/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
