apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transfer-app
  namespace: wms-proto
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/transfer
            pathType: Prefix
            backend:
              service:
                name: transfer-app
                port:
                  number: 8180
