apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-app
  namespace: wms-proto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bff-app
  template:
    metadata:
      labels:
        app: bff-app
    spec:
      imagePullSecrets:
        - name: nexus-docker-creds
      containers:
        - name: bff-app
          image: 10.96.191.117:8082/bff-app:jenkins-22
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3030
          env:
            - name: PORT
              value: "3030"
            - name: NODE_ENV
              value: local
            - name: WAREHOUSE_URL
              value: http://warehouse-app:8081
            - name: ORDER_URL
              value: http://order-app:8160
            - name: RESOURCE_URL
              value: http://resource-app:8140
            - name: INBOUND_URL
              value: http://inbound-app:8130
            - name: TRANSFER_URL
              value: http://transfer-app:8180
            - name: PIM_URL
              value: http://pim-app:8095
          readinessProbe:
            httpGet:
              path: /api/bff
              port: 3030
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/bff
              port: 3030
            initialDelaySeconds: 90
            periodSeconds: 10
