apiVersion: v1
kind: Service
metadata:
  name: warehouseapp-hazelcast
  namespace: wms-proto
spec:
  selector:
    app: warehouseapp-hazelcast
  ports:
    - name: hazelcast
      port: 5701
      targetPort: 5701
