apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-postgres
  namespace: wms-proto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-postgres
  template:
    metadata:
      labels:
        app: warehouse-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.6
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: om
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
