apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-store-app
  namespace: wms-proto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-store-app
  template:
    metadata:
      labels:
        app: front-store-app
    spec:
      imagePullSecrets:
        - name: nexus-docker-creds
      containers:
        - name: front-store-app
          image: 10.96.191.117:8082/front-store-app:proto-nexus-2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
            - name: DEPLOY_ENV
              value: proto
            - name: DB_URL
              value: jdbc:postgresql://front-store-postgres:5432/frontstoreapp
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: SERVER_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /api/front-store/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/front-store/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
