apiVersion: apps/v1
kind: Deployment
metadata:
  name: yard-app
  namespace: wms-proto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: yard-app
  template:
    metadata:
      labels:
        app: yard-app
    spec:
      imagePullSecrets:
        - name: nexus-docker-creds
      initContainers:
        - name: init-db-schemas
          image: postgres:12.8
          env:
            - name: PGPASSWORD
              value: postgres
          command:
            - sh
            - -c
            - |
              until pg_isready -h yard-postgres -p 5432 -U postgres; do
                sleep 2
              done
              psql -h yard-postgres -U postgres -d yard-db -c 'CREATE SCHEMA IF NOT EXISTS yard;'
              psql -h yard-postgres -U postgres -d yard-db -c 'ALTER DATABASE "yard-db" SET search_path TO yard, public;'
      containers:
        - name: yard-app
          image: nexus3.platform.svc.cluster.local:8082/yard-app:jenkins-6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8155
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
            - name: DEPLOY_ENV
              value: proto
            - name: DB_URL
              value: jdbc:postgresql://yard-postgres:5432/yard-db
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "yard-kafka:9094"
            - name: PIM_REST_URI
              value: "http://pim-app:8095/api/pim"
            - name: APP_HAZELCAST_NETWORK_CLUSTER_MEMBERS_0
              value: "yard-hazelcast:5701"
            - name: SERVER_PORT
              value: "8155"
          readinessProbe:
            httpGet:
              path: /api/yard/actuator/health/readiness
              port: 8155
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/yard/actuator/health/liveness
              port: 8155
            initialDelaySeconds: 180
            periodSeconds: 10
