apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
  namespace: wms-proto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      imagePullSecrets:
        - name: nexus-docker-creds
      initContainers:
        - name: init-db-schemas
          image: 10.96.191.117:8082/order-app:jenkins-2
          env:
            - name: PGPASSWORD
              value: postgres
          command:
            - sh
            - -c
            - |
              until pg_isready -h order-postgres -p 5432 -U postgres; do
                sleep 2
              done
              psql -h order-postgres -U postgres -d om -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
      containers:
        - name: order-app
          image: 10.96.191.117:8082/order-app:jenkins-2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8160
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
            - name: DEPLOY_ENV
              value: proto
            - name: DB_URL
              value: jdbc:postgresql://order-postgres:5432/om
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: order-kafka:9094
            - name: APP_HAZELCAST_NETWORK_CLUSTER_MEMBERS_0
              value: order-hazelcast:5701
            - name: SERVER_PORT
              value: "8160"
          readinessProbe:
            httpGet:
              path: /api/order/actuator/health/readiness
              port: 8160
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/order/actuator/health/liveness
              port: 8160
            initialDelaySeconds: 240
            periodSeconds: 10
