apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-app
  namespace: wms-proto
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/order
            pathType: Prefix
            backend:
              service:
                name: order-app
                port:
                  number: 8160
