apiVersion: v1
kind: Service
metadata:
  name: order-zookeeper
  namespace: wms-proto
spec:
  selector:
    app: order-zookeeper
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
