apiVersion: v1
kind: Service
metadata:
  name: mechanization-manager-postgres
  namespace: wms-proto
spec:
  selector:
    app: mechanization-manager-postgres
  ports:
    - port: 5432
      targetPort: 5432
