apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-kafka
  namespace: wms-proto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-kafka
  template:
    metadata:
      labels:
        app: resource-kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:5.4.4
          ports:
            - containerPort: 9094
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: resource-zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INTERNAL://resource-kafka:9094
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
